### ISSUE TITLE
Custom fields use machine names not ids

### ISSUE THREAD

**Issue by colemanw** [civicrm/org.civicrm.api4#37]
In api v3, you pass params like `'custom_123' => 'foo'`. This is not portable because the id of custom fields can change when migrating a site e.g. from dev to staging.

Suggested syntax in api4 (using the "group" + "name" of a custom field):

    ->addWhere('a_few_of_myfavorite_things.favorite_color', 'IN', ['blue', 'yellow'])

https://wiki.civicrm.org/confluence/display/CRM/Symbolic+Names+for+Custom+Data+and+API

**Comment by ErichBSchulz** [comment]
would that be better as 

`->addWhere('custom.business_revenues', '>', '100000')` ?

**Comment by eileenmcnaughton** [comment]
yeah - I think you are right @ErichBSchulz  - that seems safer.

**Comment by colemanw** [comment]
See https://wiki.civicrm.org/confluence/display/CRM/Symbolic+Names+for+Custom+Data+and+API

**Comment by colemanw** [comment]
Actually, as noted in the wiki, field names do not have to be unique across groups. So the syntax would include the group name. E.g. `"a_few_of_myfvorite_things.favorite_color"`

**Comment by michaelmcandrew** [comment]
just want to be explicit about the syntax here - are you suggesting removing the `custom.` prefix that you suggestion originally. I would advocate for doing so since the custom seems unecessary and the field_set.field syntax is more compact. (I've been doing this with a wrapper in API3 - not a lot but enough to feel like it is the right thing to do).

Some thoughts. Custom fields should be obvious as they will contain a `.` We might also return an array of custom field names as a helper for people that want to identify fields that are custom vs. core. I wonder if the presence of a . will be annoying in JS syntax. My guess is know / it might actually be useful to treat them as objects but wanted to put it out there...

**Comment by colemanw** [comment]
@michaelmcandrew yes I've amended the above proposal to remove the word custom.

**Comment by mickadoo** [comment]
I've got this working, not sure where I should draw the line here and say this ticket is done. I was investigating using event subscribers to set the default values as mentioned in #62 but it could be done as a separate ticket.

**Comment by mickadoo** [comment]
It was suggested to use a syntax like

`->addWhere('a_few_of_myfavorite_things.favorite_color', 'IN', ['blue', 'yellow'])`

Which I'm guessing is matching the OptionValue labels for these options. It might be confusing to have a select that functions differently from a where clause, for example in the working test right now:

```
->addSelect('MyContactFields.FavColor.label')
->addWhere('MyContactFields.FavColor', '=', 'r')
```

The select will select the label since we decided we wanted to allow selecting of different option value fields. The where uses the OptionValue value. If we changed this to accept `MyContactFields.FavColor = 'red'` then it could lead to complications later, it might not be such a problem here, but what if the option value label is numeric?

For example if it was `ContactDetails.Age = 40` should we use the numeric OptionValue.value (which can be assigned sequentially) or compare it against OptionValue.label? It's clear to us which is right, but it's ambiguous enough that I can see it causing problems later.

As it stands from my last commit it's possible to use option value fields in where clauses like

```
->addWhere('FavoriteThings.FavFood.label', 'IN', ['Corn', 'Potatoes']) // use label
->addWhere('FavoriteThings.FavFood', 'IN', [1, 2]) // same thing but using value
```

**Comment by colemanw** [comment]
You're right.That's better.
Historically the api3 does some magic which allows you to supply values OR names (not labels) of options and it will figure out which is which.
I think this explicit approach for api4 is cleaner though.
Does it work with names, e.g.

    ->addWhere('FavoriteThings.FavFood.name', 'IN', ['c', 'p']) // use name

**Comment by mickadoo** [comment]
I just checked and since it's joining on the option value table usage of any option value field should be possible in both where clauses and selects, for example:

```
->addWhere('FavoriteThings.FavFood.component_id', 'IS NULL', NULL)
```

**Comment by colemanw** [comment]
Cool.
