### ISSUE TITLE
is NOT a secure operation

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/org.civicrm.api4#43]
arising from concerns @ #41 - just need to ensure we are creating security vulnerabilities by allowing standing clauses to be `NOT`ed

**Comment by xurizaemon** [comment]
Not suggesting there's something magic or terrible about `NOT`, but rather that the more power in constructing a query we offer to clients, the more we have to secure.

The safest is a simple match, eg REST-style `GET /contact/%id`, where we know all inputs are of a specific type and there's no client input to the constructed SQL - it always looks like `WHERE id=%id` internally. (For multiple matches, an example might be `GET /contact/list/1,2,3` => `WHERE id IN (1, 2, 3)` or `GET /contact/list?parameters[name]=schulz` for a filter.)

More powerful and more dangerous is increasing the number of SQL verbs to include complex criteria. We end up building complex SQL statements and we may not correctly predict the ways in which people use or abuse them.

Because SQL offers interfaces to things an API author may not consider, eg local file reads, UNION, blind SQL via `ORDER BY SLEEP(1)` etc, it's good to guide the development of the API so that this class of risks is eliminated.

That's why I'm asking about whether we want to start exposing *any* SQL constructors to the exposed API interface, because new attacks surface in surprising ways, and we have the option to prevent an entire class of attacks or to end up plugging gaps as we learn about them.

(I suspect there's a reason I've not yet found any published API implementations that expose as much SQL to the client as we do.)

**Comment by ErichBSchulz** [comment]
well I was hoping to focus on the `NOT` operator in this issue.

To add `OR` and `NOT` was simply a refactor of the code @colemanw had written to assemble "field-operator-value" triples with `CRM_Core_DAO::createSQLFilter()`

the risk I can see is that if there is some embedded security in `CRM_Core_DAO::createSQLFilter()` (possibly even set up via some kind of hook) that allows certain "operator-value" pairs that would be broken by negation. 

For example if "postcode IN (4064)" is allowed but "postcode NOT IN (4064)" was prohibited, then relying on that logic is going to break if API4 then allows "NOT (postcode IN (4064))".

So, in summary, my niggly concern is that perhaps allowing an enclosing `NOT` in the API4 layer could break security imposed within `CRM_Core_DAO::createSQLFilter()`.

I would be surprised if it is actually a problem, but the possibility occurred to me so I thought it was worth specifically excluding (hopefully by someone who knows - otherwise I'll need to go line by line and could miss something)

**Comment by xurizaemon** [comment]
OK, I misunderstood your question & this issue! Sorry about that.

**Comment by colemanw** [comment]
I can't think of how NOT would pose a security risk off the top of my head, but I'm not omnipotent.
The ACL clauses in the query will be added no matter what (if `checkPermissions = true`) and I don't see how NOT could be used to negate them.

**Comment by ErichBSchulz** [comment]
Thanks @colemanw ! agree that the ACL clause will be safe as it is added directly to the base of the tree - I guess I have more a concern that there could be hook called from the depths in `CRM_Core_DAO::createSQLFilter()` that NOTting could fundamentally break. Happy to close this if there is none.
