### ISSUE TITLE
MultiValue Custom Data as Entities

### ISSUE THREAD

**Issue by colemanw** [civicrm/org.civicrm.api4#55]
Api4 should treat each multi-record custom data set as its own CRUD entity.

Proposed syntax (object instantiation is a slight deviation from the normal pattern to accommodate a dynamic entity class):

    Civi\Api4\CustomValue::get('MyRecords')
      ->addWhere('entity_id', '=', 123)
      ->execute();

**Comment by nganivet** [comment]
@colemanw Can we have a discussion on this? You know this is one of my topics of interest, and IMO something that will make or break API v4. You can read the article at https://codeplanet.io/principles-good-restful-api-design/ for great insight, and in particular section "Data Design and Abstraction':

> Occasionally, a Collection can represent a database table, and a Resource can represent a row within that table. However, this is not the usual case. **In fact, your API should abstract away as much of your data and business logic as possible**. It is very important that you don’t overwhelm Third-Party Developers with any complex application data, if you do they won’t want to use your API.
(emphasis mine)

IMO the proposed semantics are much too close to the physical database schema, and it might not extend to other implementations - ie. what about word replacements or other entities that are implemented using a serialized PHP array? Also the syntax is going to be very cumbersome if we have to insert a complete Contact record in the database.

I would personally rather see a more 'business-oriented' approach, where the multi-value attributes are not exposed as their own entities but as attributes of the parent entity with specific multi-valued oriented 'methods' that complement the regular getter/setter methods.

But obviously we would need more research to see how other APIs are dealing with multi-valued attributes to then make an informed decision, rather than purely rely on our intuition.

**Comment by nganivet** [comment]
WRT research, here is the OSDI implementation of a contact record: https://opensupporter.github.io/osdi-docs/people.html. All multi-valued fields are exposed as arrays, and they resolve the multi-value field updates as such (cf. Scenario: Modifying a person (PUT)):

> Note: Modifying members of an array separately is not supported. To change the contents of an array, first GET the current contents and then PUT back only those you wish to keep.

I am personally much more comfortable with this model than the "each multi-valued attributes gets it's own Entity". IMO it greatly simplifies insertion/retrieval, and is much more consumer-friendly than dealing with many derived entities & multiplying API calls for such insertion/retrievals. It remains to be seen how this model would support the complex queries we can do as part of the 'Advanced search' screen for example, and I'm sure many others, but let's at least give this model a closer look before discarding it for the database-centric model of API v3.

**Comment by colemanw** [comment]
@nganivet I don't see this as an either/or situation. We need a generic way to join one-to-many records and retrieve them in a useful way. For contacts we need to be able to do this with phones, emails, addresses, etc. Adding a muti-record custom entity allows us to be consistent and follow the same pattern for custom data.

**Comment by totten** [comment]
Haven't we discussed this already? For anyone who's first exposure is here, let me try to recount a perspective.

For me, multi-value custom-data (MVCD) fills a particular niche: it's a mechanism for quickly implementing a new business entity. (This is very different from single-value custom-data.) MVCD is a scaffolding/RAD tool (and a very opinionated one). Compared to writing custom code, MVCD comes with a trade-off -- easier implementation but less depth/nuance. But its essential function is making a new business entity.

Talk about "business" or "data" layers is very abstract, so it helps me to have concrete example of MVCD. Take https://github.com/civicrm/civihr/tree/staging/hrvisa . It defines a new entity for tracking visa/immigration information:
 * With MVCD, you can prototype it by clicking in the UI, then dump it to XML, and ship that as an extension.
 * Without MVCD, you need to piece together a bunch of things (XML files, build-scripts, DAOs, BAOs, API's, hook_civicrm_entityTypes -- and that's not even getting into the UI stuff like the "Advanced Search" or "View Contact" screen).

Of course, MVCD isn't perfect: you get a bunch of UIs+services for free/cheap, and mostly they're a workable baseline, but what if you don't like one of them? For example, maybe you like the "Advanced Search" pane but dislike the layout in "View Contact => Visas". You feel it's too generic; you'd prefer to arrange the various fields/subsections/rows/help-text/add-buttons/remove-buttons in a different way. That means writing a better form.

There's a lot of judgment about how to layout/present the elements in "View Contact => Visas", and you might go through user-stories, etc. But even without that, we can still make some basic assumptions about how this block needs to work:
 * You'll need a way to read/display the existing Visas.
 * You'll need a way to add new Visas or update existing Visas.
 * (Mostly likely) You'll want hooks to allow more specialized, subjective business rules. (Like "Send an email alert about new visas to the immigration attorney" or "Only allow Visas where the target nation is US or Canada" or "Send an automated reminder 2 weeks before a Visa expires.")
 * (Most likely) You'll want a different policy for the role-based permissions of Visas versus Contacts vs Contributions.
 * The identity of each Visa record significant. (`Visa #123` should remain `Visa #123` even if someone deletes the erroneous/superfluous `Visa #107`.)

The key point is that *the Visa is a business entity*. The business rationales/needs/issues are different for tracking "Visas" vs "Email Addresses" vs "Contributions". The users are most likely different. (Overlapping but different.)

Could one imagine some other regime? Sure. Maybe you don't trust admins/site-builders to get involved with modelling. Maybe you'd prefer to say "Let's redesign the full-stack for MVCD/scaffolding before doing anything in APIv4." But if you accept that MVCD is a legit way to define an entity like "Visa", and if you accept that developers should have programmatic access to these entities in APIv4, then it follows naturally that APIv4 should present MVCD entities the same way as all its other entities.

**Comment by nganivet** [comment]
@colemanw My point exactly. I would like you to consider having phone, email, address and other multi-valued fields as 'multi-valued attributes' of contact rather than their own business entity. Because if we start making these their own entities, then we will arrive in the same mess as API v3 where line items, entity tag, activity contact, participant payment, entity financial transaction, price field value, etc. were all implemented as their own 'entities'. Can anyone explain what 'ActivityContact' or 'PriceFieldValue' has to do with business at all? Nothing ... they are just database schema tables. The same is true for the multi-valued custom data sets that you are proposing. If we sit down together, study what the market is offering, I am sure we can come to a middle-ground solution that would take the best of both worlds.

@totten You are getting sidetracked, this discussion has nothing to do with new business entities, but with how we code multi-valued attributes in an existing entity. For example, how would you code the multi-valued 'approval' attribute for your visa entity? Each approval has a date and department (ie. Immigration and Naturalization Service, Department of Labor and Employment, ...). Each visa will need different approvals based on it's type, position applied for, and place of work. Will you create a multi-valued field to hold these approval? Or create a new 'business entity'? If so, is it really a business entity or a database table?

**Comment by eileenmcnaughton** [comment]
I think we need to be careful about derailing this funded api project with a wishlist for a different, but complementary, project We have abandoned the apiv4 multiple times because of the desire for it to be a pseudo-rewrite of CiviCRM. The difference this time is that there is a funded project to add the extension as envisaged by @totten @colemanw (and which I believe will allow us to get rid of technical blockers).

I think using the api-in-an-extension-as-wrapper is a good model for replacing a lot of the internals and in previous discussions you were going to do some preliminary work on how that business api might be. I would encourage you to continue with that work in an extension, which I believe would be complementary to this one, and could potentially ship with core.

I think the issue here is a fairly technical issue in this ticket, and it's getting overloaded with a big-picture discussion that we have had many many times before (and which has killed previous api v4 efforts). Let's focus api v4 discussion on the funded project and have  discussion on scoping the potential business api project separately.

I think the key thing that is missing for the business-api project to go ahead is resources. I don't know the steps required to get it beyond a concept - but I think the prototype we've discussed when we've had this discussion over the past few years would be a good start.

**Comment by totten** [comment]
>  how we code multi-valued attributes in an existing entity. For example, how would you code the multi-valued 'approval' attribute for your visa entity?

This smells like a miscommunication. Compare these situations:

 * `CustomGroup[name=Visa,is_multiple=1]` + `CustomField[name=approval,html_type=Select]`. 
 * `CustomGroup[name=Visa,is_multiple=0]` + `CustomField[name=approval,html_type=MultiSelect]`.

Both could be plausibly labeled "MultiValue Custom Data". This ticket is supposed to be about the first scenario and how we expose it in the API. (The example in Coleman's original description makes sense in the first scenario. Nicolas's feedback about embedding within `Contact` makes sense in the second scenario. But neither makes sense if you mix-up the scenarios/comments.)

An example use-case for the original issue would be "find all Visas for Contact `#123` which are in the `requested` or `rejected` status", e.g.

```php
Civi\Api4\Custom::group('Visa')->get()
  ->addWhere('entity_id', '=', 123)
  ->addWhere('status', 'IN', array('requested','rejected'))
  ->execute();
```

How would one get this data in APIv3? You could dig into `CustomValue` API, but it's sadistic. Please try to see issue #55 for what it's intended to be -- a less sadistic alternative to `CustomValue` API.

**Comment by mickadoo** [comment]
@nganivet: I agree that join tables like "ActivityContact" shouldn't be exposed if possible, but I don't think we should hide legitimate entities like "Email" or "Phone" under the Contact API. Nesting related entities is great for API consumers like FE developers because they can get whatever they want in a single request, but for API developers it makes things more complex. For example instead of just updating a single entity in "create" request I have to check all related entities in the payload, validate the data and update each of them. In my experience API consumers will always want more related data, but to build a consistent, reliable interface it's best to keep it simple.

---

I'm looking at this ticket to see how I can start working on it, but it would be good to know if it's something we really want before I do. I can definitely see the use case like with Visa, as mentioned. We really should be pushing for a best practice of _either_ creating a new entity with the BAO etc. _or_ using a CustomGroup. 

It seems like the cleaner way would be to use the BAO because it's the default way things are done in core. If we encourage the CustomGroup approach we will eventually end up with situations like @totten mentioned where people want to customize the behaviour of their new entities more, e.g. creating a new activity whenever the Visa was updated. I'm sure there are ways around this, but we should ask first if that's the direction we want to go.

Pros:

:slightly_smiling_face: Allows non-developers to add business entities
:slightly_smiling_face: Simpler than the alternative for new entity creation
:slightly_smiling_face: We have existing methods to display custom data (e.g. on contact summary)

Cons:

:slightly_frowning_face: New entities cannot be customized as much as regular BAO entities
:slightly_frowning_face: Breaks convention with every other entity interaction
:slightly_frowning_face: Will lead to more requests for customization of these MVCD entities
:slightly_frowning_face: All existing naming suggests that these are custom fields, or custom data, and not separate entities
:slightly_frowning_face: We only support FKs to contacts for now, it's likely MVCD entities will require FKs to any entity

**Comment by colemanw** [comment]
I'm trying to understand your concerns about this. Yes, multivalue custom data has limitations (it only applies to contacts, it's not as customizable as other BAOs) but in that way it's pretty much like the Phone or Website entities. IMO we should treat MVCD the same as those entities.

**Comment by mickadoo** [comment]
I've been playing around with how this might work. As a branch from the non-static branch I tried using the existing API classes for custom entities (which I've started calling these instead of MVCD). They would allow you to use custom entity APIs in the same way you use existing APIs. The difference would be hidden away in the request handlers. The only other difference I can think is that `entity_id` will always be required.

Anyway, [here](https://github.com/mickadoo/api4/blob/e9cd008ff85ca16309600a1321006f1177ca8750/tests/phpunit/Api/CustomEntityApiTest.php) is a test sample, and the syntax

```
    $customEntityApi = $container->get('contact_visa.api');    
    $customEntityApi->request('create', array(
      'entity_id' => $contact['id'],
      'expiration' => '2020-01-01',
      'place_of_issue' => 'Bordeaux'
    ));
```

Where `visa` is a custom group with two custom fields, `expiration` and `place_of_issue`.

It also handles "is_multi" [differently](https://github.com/mickadoo/api4/blob/3928eb9833324b2f1f2b93313db743783faf3b8b/Civi/Api4/Service/CustomEntityService.php#L55). 

If it is multiple then it checks for the "id" parameter, if it isn't set it creates a new row, just like the other API calls. If "id" is set it'll update it.

For non-multiple it will check for any existing row for that "entity_id" and update it if it exists. If it doesn't it'll create it.

The data can be accessed using either the custom entity API or the API for the base entity for example:

```
    $getParams = new GetParameterBag();
    $getParams->addSelect('first_name');
    $getParams->addSelect('ContactVisa.expiration');
    $getParams->addSelect('ContactVisa.place_of_issue');
    $contactResult = $contactApi->request('get', $getParams);
```

Where a single contact with two related visas exist will return:

```
[
  {
    "id": "5",
    "first_name": "First",
    "ContactVisa": [
      {
        "expiration": "2010-01-01 00:00:00",
        "place_of_issue": "Bordeaux",
        "id": "1"
      },
      {
        "expiration": "2020-01-01 00:00:00",
        "place_of_issue": "Paris",
        "id": "2"
      }
    ]
  }
]
```

**Comment by nganivet** [comment]
Michael,

Thanks for your work on this. Your syntax is elegant and fulfills both 
aspects discussed: access through the parent entity and a specific API.

A couple questions:
Is it possible to add all fields of the ContactVisa with 
$getParams->addSelect('ContactVisa'); or 
$getParams->addSelect('ContactVisa.*'); ?
Is this syntax also working with the 'system' sub-entities, like 
address/phone/email. For example if I want to query a contact and get 
all the phone numbers associated with this contact? Can I then 
$getParams->addSelect('Phone'); or $getParams->addSelect('Phone.*'); ?
Thanks,
--Nicolas.
------ Original Message ------

**Comment by mickadoo** [comment]
@nganivet thanks for the feedback. Since I added that example I've also added a handler for get requests so you can do get requests for these custom entities. I have an example test [here](https://github.com/mickadoo/api4/blob/11ed6bbd2834569511e43ae2f4fad43b81783650/tests/phpunit/Api/CustomEntityGetTest.php#L39). Right now this is fairly basic, and returns _all_ the custom entity fields. 

It doesn't nicely handle fields that are linked to option groups or select fields. We might decide to ditch it because of this. Ideally it would act similarly to regular API calls, but I'm not sure this is possible.

Related to that, I am a bit worried that developers will expect _all_ the features available through core entity API calls (such as joining tables). My original plan was to use the regular `Api4SelectQuery` but this query is so tied to the idea that the entity you pass in to it will have a BAO class that I gave up on using it for custom entities.

I did consider the possibility of using the `*` option. I'm not 100% sure about it because It's becoming more like SQL than an actual API request :-) But of course I can see the use case.  I can add a test for this if there's demand for it, or you can if you like by forking my fork (that sounds wrong) and making a PR to it.
